# Generated by Django 5.1.4 on 2025-01-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcdata',
            name='applicant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lcdata',
            name='expiry_date',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='lcdata',
            name='date_of_issue',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='lcdata',
            name='lc_number',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
